# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindGameApp', '0002_auto_20180121_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='fb_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
